backend:
  name: github
  repo: MapyWiedzy/edukacja
  branch: main
  auth_type: oauth
  base_url: https://api.github.com
  auth_endpoint: https://github.com/login/oauth/authorize
  token_endpoint: https://github.com/login/oauth/access_token
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "home"
    label: "Strona Główna"
    files:
      - file: "content/home/_index.md"
        name: "home_page"
        label: "Strona Główna"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Data", name: "date", widget: "datetime" }
          - { label: "Treść", name: "body", widget: "markdown" }
  - name: "geografia"
    label: "Geografia"
    folder: "content/geografia"
    create: true
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Treść", name: "body", widget: "markdown" }