backend:
  name: github
  repo: MapyWiedzy/edukacja
  branch: main
  client_id: "Ov23lizPm0MynMUdCjjY" # Wstaw poprawny Client ID
  client_secret: "e80ac06dd04300d963ab5f2023839505b30b7c66" # Wstaw poprawny Client Secret
  auth_type: oauth
  scope: repo # Dodaj scope dla repozytorium
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "home"
    label: "Strona Główna"
    files:
      - file: "content/home/_index.md"
        name: "home_page"
        label: "Strona Główna"
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Data", name: "date", widget: "datetime" }
          - { label: "Treść", name: "body", widget: "markdown" }
  - name: "geografia"
    label: "Geografia"
    folder: "content/geografia"
    create: true
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Treść", name: "body", widget: "markdown" }